### PR TITLE
Move vsr to include/vsr and start cleanup of toplevel folder

### PR DESCRIPTION
**Pull request by tingelst**
This PR moves the vsr include directory to `include/vsr` as a first step to clean up the top level folder. The examples that is affected by this move is updated and building successfully. I propose to start using `#include <vsr/folder/file.h>` for includes as shown in `examples/xFabrikChain.cpp`

### CODE REVIEW

**Comment by wolftype** [comment]
thanks lars -- could you please explain a bit more the motivations behind this organizational change?

i've seen libraries where the headers are in a folder with the library name, and also 
libraries where the headers are in a folder called include ("include/folder/filename.h"), but not so sure i've seen libraries where it goes "include/libname/folder/filename.h"

**Comment by tingelst** [comment]
It really just is that I think it is cleaner, and most of the libraries I use have an include folder in the top level. 

An example is `#include <vsr/draw/vsr_cga3D_draw.h>`. I think this clean and readable. 

I might also propose to change to `#include <vsr/draw/cga3d_draw.h>`, but that can wait to a later PR:)

**Comment by wolftype** [comment]
got it thanks lars, keep cleaning!

p

**Comment by wolftype** [comment]
i also agree that the "vsr_" prefix is redundant now ...

**Pull request merged**
